// Package iproto contains IPROTO constants.
//
// The package code generated from:
//
//	Repository: https://github.com/tarantool/tarantool.git
//	Tag or branch: master
//	Commit: 22d7636b521fd2e18104852ba1e0c206825f92a5
package iproto

// Code generated by generate.sh; DO NOT EDIT.
