// Package iproto contains IPROTO constants.
//
// The package code generated from:
//
//	Repository: https://github.com/tarantool/tarantool.git
//	Tag or branch: master
//	Commit: 72eeaee8b25b86486b041e59cc48afb7e015365e
package iproto

// Code generated by generate.sh; DO NOT EDIT.
