// Package iproto contains IPROTO constants.
//
// The package code generated from:
//
//	Repository: https://github.com/tarantool/tarantool.git
//	Tag or branch: master
//	Commit: c5f5ee0d51c5ece443f56d19222400893fa68a7f
package iproto

// Code generated by generate.sh; DO NOT EDIT.
