// Code generated by "stringer -type=Feature"; DO NOT EDIT.

package iproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IPROTO_FEATURE_STREAMS-0]
	_ = x[IPROTO_FEATURE_TRANSACTIONS-1]
	_ = x[IPROTO_FEATURE_ERROR_EXTENSION-2]
	_ = x[IPROTO_FEATURE_WATCHERS-3]
	_ = x[IPROTO_FEATURE_PAGINATION-4]
}

const _Feature_name = "IPROTO_FEATURE_STREAMSIPROTO_FEATURE_TRANSACTIONSIPROTO_FEATURE_ERROR_EXTENSIONIPROTO_FEATURE_WATCHERSIPROTO_FEATURE_PAGINATION"

var _Feature_index = [...]uint8{0, 22, 49, 79, 102, 127}

func (i Feature) String() string {
	if i < 0 || i >= Feature(len(_Feature_index)-1) {
		return "Feature(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Feature_name[_Feature_index[i]:_Feature_index[i+1]]
}
