// Code generated by generate.sh; DO NOT EDIT.

package iproto_test

import (
	"testing"

	"github.com/tarantool/go-iproto"
)

func TestFeature(t *testing.T) {
	cases := []struct {
		Feature iproto.Feature
		Str     string
		Val     int
	}{

		{iproto.IPROTO_FEATURE_STREAMS, "IPROTO_FEATURE_STREAMS", 0},
		{iproto.IPROTO_FEATURE_TRANSACTIONS, "IPROTO_FEATURE_TRANSACTIONS", 1},
		{iproto.IPROTO_FEATURE_ERROR_EXTENSION, "IPROTO_FEATURE_ERROR_EXTENSION", 2},
		{iproto.IPROTO_FEATURE_WATCHERS, "IPROTO_FEATURE_WATCHERS", 3},
		{iproto.IPROTO_FEATURE_PAGINATION, "IPROTO_FEATURE_PAGINATION", 4},
	}

	for _, tc := range cases {
		t.Run(tc.Str, func(t *testing.T) {
			if tc.Feature.String() != tc.Str {
				t.Errorf("Got %s, expected %s", tc.Feature.String(), tc.Str)
			}
			if int(tc.Feature) != tc.Val {
				t.Errorf("Got %d, expected %d", tc.Feature, tc.Val)
			}
		})
	}
}
