// Code generated by generate.sh; DO NOT EDIT.

package iproto

// IPROTO feature constants, generated from
// tarantool/src/box/iproto_features.h
type Feature int

const (
	// Streams support: IPROTO_STREAM_ID header key.
	IPROTO_FEATURE_STREAMS Feature = 0
	// Transactions in the protocol:
	// IPROTO_BEGIN, IPROTO_COMMIT, IPROTO_ROLLBACK commands.
	IPROTO_FEATURE_TRANSACTIONS Feature = 1
	// MP_ERROR MsgPack extension support.
	//
	// If a client doesn't set this feature bit, then errors returned by
	// CALL/EVAL commands will be encoded according to the serialization
	// rules for generic cdata/userdata Lua objects irrespective of the
	// value of the msgpack.cfg.encode_errors_as_ext flag (by default
	// converted to a string error message). If the feature bit is set and
	// encode_errors_as_ext is true, errors will be encoded as MP_ERROR
	// MsgPack extension.
	IPROTO_FEATURE_ERROR_EXTENSION Feature = 2
	// Remote watchers support:
	// IPROTO_WATCH, IPROTO_UNWATCH, IPROTO_EVENT commands.
	IPROTO_FEATURE_WATCHERS Feature = 3
	// Pagination support:
	// IPROTO_AFTER_POSITION, IPROTO_AFTER_TUPLE, IPROTO_FETCH_POSITION
	// request fields and IPROTO_POSITION response field.
	IPROTO_FEATURE_PAGINATION Feature = 4
)
