// Code generated by generate.sh; DO NOT EDIT.

package iproto_test

import (
	"testing"

	"github.com/tarantool/go-iproto"
)

func TestFlag(t *testing.T) {
	cases := []struct {
		Flag iproto.Flag
		Str  string
		Val  int
	}{

		{iproto.IPROTO_FLAG_COMMIT, "IPROTO_FLAG_COMMIT", 1 << 0},
		{iproto.IPROTO_FLAG_WAIT_SYNC, "IPROTO_FLAG_WAIT_SYNC", 1 << 1},
		{iproto.IPROTO_FLAG_WAIT_ACK, "IPROTO_FLAG_WAIT_ACK", 1 << 2},
	}

	for _, tc := range cases {
		t.Run(tc.Str, func(t *testing.T) {
			if tc.Flag.String() != tc.Str {
				t.Errorf("Got %s, expected %s", tc.Flag.String(), tc.Str)
			}
			if int(tc.Flag) != tc.Val {
				t.Errorf("Got %d, expected %d", tc.Flag, tc.Val)
			}
		})
	}
}
